env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - main: ./cmd/diceware/diceware.go
    id: "diceware"
    binary: diceware
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
